# Generated by Django 4.2.4 on 2023-08-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world_news', '0020_latestarticlespost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentNewsTitle',
        ),
    ]
