# Generated by Django 4.2.4 on 2023-08-25 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world_news', '0021_delete_commentnewstitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentNewsTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=255, null=True)),
                ('news_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world_news.newstitle')),
            ],
        ),
    ]
