# Generated by Django 4.2.4 on 2023-08-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world_news', '0022_commentnewstitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=120)),
                ('date_of_publishing', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
        ),
    ]
